#!/bin/sh

## Get my own path

path="$( dirname "$0" )"


## Get info about board/hardware and mac address

. /lib/ar71xx.sh

board="$(ar71xx_board_name)"

case "$board" in
	tl-wdr3600|\
	tl-wdr4300)
	        macaddr="$(uci get wireless.radio1.macaddr)"
		;;
	*)
		macaddr="$(uci get wireless.radio0.macaddr)"
		;;
esac


## Key-Upload

"$path/upload_keys" "$macaddr" &
	

## MAC-Adresse fuer interface auswuerfeln

oIFS="$IFS"
IFS=":"
set -- $macaddr; IFS="$oIFS"

b2mask=0x02

macaddr="$( printf "%02x:%s:%s:%02x:%s:%s" $(( 0x$1 | $b2mask )) $2 $3 $(( (0x$4 + 1) % 0x100 )) $5 $6 )"


if [ "$(uci get freifunk.@bandwidth[0].enabled)" = 1 ]; then
	tc qdisc add dev "$INTERFACE" root tbf rate "$( uci get freifunk.@bandwidth[0].upstream )kbit" latency 50ms burst 2k

	tc qdisc add dev "$INTERFACE" handle ffff: ingress
	tc filter add dev "$INTERFACE" parent ffff: u32 match u8 00 00 at 0 police rate "$( uci get freifunk.@bandwidth[0].downstream )kbit" burst 10k drop flowid :1
fi


## MAC-Adresse setzen

ip link set address "$macaddr" up dev "$INTERFACE"

( pwd; set ) > /tmp/XXX

exit 0
	
